export const POPULAR_GAMES_LOADED = "POPULAR_GAMES_LOADED";
export const NEW_GAMES_LOADED = "NEW_GAMES_LOADED";
export const FREE_GAMES_LOADED = "FREE_GAMES_LOADED";

export const POPULAR_CAROUSEL_INDEX_CHANGED = "POPULAR_CAROUSEL_INDEX_CHANGED";
export const NEW_CAROUSEL_INDEX_CHANGED = "NEW_CAROUSEL_INDEX_CHANGED";
export const FREE_CAROUSEL_INDEX_CHANGED = "FREE_CAROUSEL_INDEX_CHANGED";

export const GAME_LOADED = "GAME_LOADED";

export const PICS_LOADED = "PICS_LOADED";

export const SEARCH_QUERIED = "SEARCH_QUERIED";

export const SEARCHED_GAMES_LOADED = "SEARCHED_GAMES_LOADED";

